# Generated by Django 4.1.4 on 2023-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intent', models.CharField(max_length=150)),
                ('motivation', models.CharField(max_length=150)),
                ('applicability', models.CharField(max_length=150)),
                ('structure', models.TextField()),
                ('participant_collaborations', models.CharField(max_length=150)),
                ('consequences', models.CharField(max_length=150)),
                ('implementation', models.CharField(max_length=150)),
                ('related_patterns', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'pattern',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatternCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'pattern_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatternCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'pattern_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatternMl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intent', models.CharField(max_length=1000)),
                ('problem', models.CharField(max_length=1000)),
                ('discussion', models.CharField(max_length=1000)),
                ('structure', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'pattern_ml',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemPatternMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem_pattern_match',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
