# Generated by Django 4.1.7 on 2023-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("correct_category", models.IntegerField()),
                ("overview", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MyProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design_problem", models.TextField()),
                ("correct_pattern", models.TextField()),
            ],
        ),
    ]
