# Generated by Django 4.1.4 on 2023-03-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_pal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mypattern',
            table='my_pattern',
        ),
        migrations.AlterModelTable(
            name='myproblem',
            table='my_problem',
        ),
    ]
